### ISSUE TITLE
`npm install` fails

### ISSUE THREAD

**Issue by abyss-outpost** [steveblue/fa-boilerplate#1]
The final step fails to install packages through NPM. Should I contact Node-SASS like it suggests?

...
`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/maeoll/Dropbox/repositories/fa-boilerplate/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "/opt/local/bin/node" "/opt/local/bin/npm" "install"
npm ERR! node v0.12.3
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.9.6 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.9.6 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by steveblue** [comment]
@abyss-outpost You most likely have to uninstall sass on your system and try again.

**Comment by abyss-outpost** [comment]
Hello, thanks for your response. I tried that, but it still doesn't work. I looked in the package.json file and saw this:
    "node-sass":"=1.2.3",

Is that supposed to be 1.2.3? I thought the current version is 3.1.2?

**Comment by abyss-outpost** [comment]
Created a pull request which fixed the issue. Thanks!
